--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/RelicsPE
build-by-default: true
branches:
- main
projects:
  RelicsPE:
    path: ""
    icon: pic.gif
    libs: 
      - src: "Paroxity/Commando/Commando"
        version: "^3.2.0"
    lint: false
...
