name: RelicsPE
version: 1.0.0-ALPHA
author: Terpz710
api: 5.0.0
main: Terpz710\RelicsPE\Relics
description: Simple relics for PocketMine-MP

permissions:
  relicspe.cmd:
    description: Allows you to spawn in relics.
    defualt: op
